-- USER table (renamed to app_user)
create table app_user (
   id            number generated by default as identity primary key,
   first_name    varchar2(100) not null,
   last_name     varchar2(100) not null,
   email         varchar2(150) not null unique,
   password_hash varchar2(255) not null,
   phone_number  varchar2(20) not null unique
);

-- CUSTOMER
create table customer (
   id number primary key,
   constraint fk_customer_user foreign key ( id )
      references app_user ( id )
         on delete cascade
);

-- SALES
create table sales (
   id         number primary key,
   store_name varchar2(150) not null,
   constraint fk_sales_user foreign key ( id )
      references app_user ( id )
         on delete cascade
);

-- ADDRESS (fixed spelling)
create table address (
   id           number generated by default as identity primary key,
   user_id      number not null,
   full_address clob not null,
   constraint fk_address_user foreign key ( user_id )
      references app_user ( id )
         on delete cascade
);

-- CATEGORY
create table category (
   id   number generated by default as identity primary key,
   name varchar2(100) not null
);

-- PRODUCT
create table product (
   id          number generated by default as identity primary key,
   user_id     number not null,
   category_id number not null,
   name        varchar2(200) not null,
   price       number(10,2) not null,
   stock       number default 0,
   constraint fk_product_user foreign key ( user_id )
      references sales ( id )
         on delete cascade,
   constraint fk_product_category foreign key ( category_id )
      references category ( id )
);

-- PICTURE
create table picture (
   id         number generated by default as identity primary key,
   product_id number not null,
   image_path varchar2(500) not null,
   constraint fk_picture_product foreign key ( product_id )
      references product ( id )
         on delete cascade
);

-- ORDER (renamed to orders)
create table orders (
   id           number generated by default as identity primary key,
   user_id      number not null,
   address_id   number not null,
   total_price  number(10,2) not null,
   order_status varchar2(20) default 'pending',
   order_date   timestamp default current_timestamp,
   constraint chk_order_status
      check ( order_status in ( 'pending',
                                'processing',
                                'shipped',
                                'delivered',
                                'cancelled' ) ),
   constraint fk_orders_user foreign key ( user_id )
      references customer ( id ),
   constraint fk_orders_address foreign key ( address_id )
      references address ( id )
);

-- ORDER ITEM
create table order_item (
   id         number generated by default as identity primary key,
   order_id   number not null,
   product_id number not null,
   price      number(10,2) not null,
   quantity   number default 1,
   constraint fk_orderitem_order foreign key ( order_id )
      references orders ( id )
         on delete cascade,
   constraint fk_orderitem_product foreign key ( product_id )
      references product ( id )
);

-- PAYMENT
create table payment (
   id             number generated by default as identity primary key,
   order_id       number not null unique,
   payment_method varchar2(50) not null,
   payment_status varchar2(50) default 'pending',
   constraint fk_payment_order foreign key ( order_id )
      references orders ( id )
         on delete cascade
);

-- CARD PAYMENT
create table payment_by_card (
   id          number primary key,
   card_number varchar2(20) not null,
   cvv         varchar2(4) not null,
   end_date    date not null,
   constraint fk_card_payment foreign key ( id )
      references payment ( id )
         on delete cascade
);

-- CASH
create table cash_on_delivery (
   id          number primary key,
   verify_code varchar2(20),
   constraint fk_cash_payment foreign key ( id )
      references payment ( id )
         on delete cascade
);

-- CART
create table cart (
   id      number generated by default as identity primary key,
   user_id number not null unique,
   constraint fk_cart_user foreign key ( user_id )
      references customer ( id )
         on delete cascade
);

-- CART ITEM
create table cart_item (
   id         number generated by default as identity primary key,
   cart_id    number not null,
   product_id number not null,
   quantity   number default 1,
   constraint fk_cartitem_cart foreign key ( cart_id )
      references cart ( id )
         on delete cascade,
   constraint fk_cartitem_product foreign key ( product_id )
      references product ( id )
         on delete cascade
);
